const SELECTED_REGION_COLOR = "#008db8";
const HOVER_COLOR = "#00c3ff";
const DEFAULT_COLOR = "#fff";
const REGIONS_NUM = 255;
const MAXIMUM_QUERY_RESULTS = 5;

export {
  SELECTED_REGION_COLOR,
  HOVER_COLOR,
  DEFAULT_COLOR,
  REGIONS_NUM,
  MAXIMUM_QUERY_RESULTS,
};
